name: Terraform Apply Plan from Issue
on:
  workflow_dispatch:
    inputs:
      commit:
        description: Commit SHA to get the plan from
        required: true

jobs:
  terraform_apply_plan:
    name: Terraform Apply Plan

    runs-on: ubuntu-20.04

    # Set a timeout on the run
    timeout-minutes: 5

    env:
      TF_VAR_PROJECT: ${{ secrets.GCP_PROJECT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Plan
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.OCTODEMO_OCTODEMOBOT_TOKEN }}
          workflow: terraform_plan_issue.yml
          commit: ${{ github.event.inputs.commit }}
          name: plan
          path: ./

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.0.1
        with:
          terraform_version: 0.12.29
          terraform_wrapper: true

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v0.1.0
        with:
          terragrunt_version: 0.23.32

      - name: Authenticate with GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        with:
          version: 303.0.0
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        run: terragrunt init

      - name: Show Plan
        run: terragrunt show ./terraform_plan

      - name: Terraform Apply
        run: terragrunt apply -auto-approve -no-color ./terraform_plan